services:
  postgres:
    image: postgres:latest
    container_name: nexus_sales_rag_db
    environment:
      POSTGRES_DB: sales_rag_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    name: nexus_sales_rag_postgres_data
